# Generated by Django 3.1.6 on 2021-08-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='periodo',
            fields=[
                ('codigo', models.IntegerField(default='999', primary_key=True, serialize=False)),
                ('Fecha_inicio', models.DateField(default='')),
                ('Fecha_final', models.DateField(default='')),
            ],
        ),
    ]
